import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from '../components/Navbar.jsx';
import HomePage from '../components/HomePage/HomePage.jsx';
import Footer from '../components/HomePage/Footer.jsx';
import FooterMenu from "../components/HomePage/FooterMenu"



export default function Home() {
  return (
    <div>

      <Head>
        <title>Boxoniq App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <HomePage />
      <Footer />
      <FooterMenu />






    </div>
  )
}
